server:
  port: 8080
  servlet:
    context-path: /morpheus

spring:
  application:
    name: morpheus
  aot:
    enabled: false
  kafka:
    bootstrap-servers: pkc-p11xm.us-east-1.aws.confluent.cloud:9092
    topic:
      msk-topic: msk-topic
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="KA6UMHGVOAVWB52M"
        password="DhKEO7BHQLN2lktD3eQwZMYRS6fKjXS0Dbu+7OCmwmNolIAwU4fCFKPXkDrBw9TH";
    listener:
      concurrency: 10
    consumer:
      group-id: mks-topic-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.apache.kafka: ERROR